name: first-worlflow
on:
  push:
    branches: [ master ]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: tannhutdocker
          password: 754ba0ee-d722-44c1-ae8f-72fc6d93a44f